site_name: API
site_description: Reposit√≥rio da API do sistema de Gerenciamento de Alunos
repo_url: https://github.com/Non-Devs/gerencial-API
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/Non-Devs">Non-Devs</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
